// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuU0IwbnQA02SPgSBmBhkeZIZIaqgQ2YE',
    appId: '1:5629801777:web:beb8498456e31e5ee12c10',
    messagingSenderId: '5629801777',
    projectId: 'buddy-alarm',
    authDomain: 'buddy-alarm.firebaseapp.com',
    storageBucket: 'buddy-alarm.appspot.com',
    measurementId: 'G-SZVSXN98P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnPiOHOCvTipMsmfqqy-K3SLFtr3E1tc',
    appId: '1:5629801777:android:1a24d4c2a4ff1182e12c10',
    messagingSenderId: '5629801777',
    projectId: 'buddy-alarm',
    storageBucket: 'buddy-alarm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkExLSYgT3DirnSGOAYmiRnTU5CJgbJjc',
    appId: '1:5629801777:ios:ed92b6e516a1eebde12c10',
    messagingSenderId: '5629801777',
    projectId: 'buddy-alarm',
    storageBucket: 'buddy-alarm.appspot.com',
    iosClientId: '5629801777-ktl6n7nv745qepjdp3k7elmt97qgcv84.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddyAlarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkExLSYgT3DirnSGOAYmiRnTU5CJgbJjc',
    appId: '1:5629801777:ios:7a019010ad96fb53e12c10',
    messagingSenderId: '5629801777',
    projectId: 'buddy-alarm',
    storageBucket: 'buddy-alarm.appspot.com',
    iosClientId: '5629801777-mp5vbo3v6gs2dk22hncbj5ftbtd4mr1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddyAlarm.RunnerTests',
  );
}
